// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	User struct {
		ID, Login, Password, AuthKey, CreatedAt, LastActivityAt, StatusID string
	}
	VfsFile struct {
		ID, FolderID, Title, Path, Params, IsFavorite, MimeType, FileSize, FileExists, CreatedAt, StatusID string

		Folder string
	}
	VfsFolder struct {
		ID, ParentFolderID, Title, IsFavorite, CreatedAt, StatusID string

		ParentFolder string
	}
	Approach struct {
		ID, ExerciseID, Reps, Weight, Duration, CreatedAt, StatusID string

		Exercise string
	}
	Category struct {
		ID, ParentCategoryID, Title, SiteUserID, StatusID string

		ParentCategory, SiteUser string
	}
	Exercise struct {
		ID, Title, CategoryID, SiteUserID, TypeID, StatusID string

		Category, SiteUser string
	}
	Training struct {
		ID, SiteUserID, ApproachIDs, StartedAt, EndedAt, StatusID string

		SiteUser string
	}
	SiteUser struct {
		ID, TgID, CreatedAt, LastActivityAt, StatisticID, StatusID, ApiKey string
	}
}{
	User: struct {
		ID, Login, Password, AuthKey, CreatedAt, LastActivityAt, StatusID string
	}{
		ID:             "userId",
		Login:          "login",
		Password:       "password",
		AuthKey:        "authKey",
		CreatedAt:      "createdAt",
		LastActivityAt: "lastActivityAt",
		StatusID:       "statusId",
	},
	VfsFile: struct {
		ID, FolderID, Title, Path, Params, IsFavorite, MimeType, FileSize, FileExists, CreatedAt, StatusID string

		Folder string
	}{
		ID:         "fileId",
		FolderID:   "folderId",
		Title:      "title",
		Path:       "path",
		Params:     "params",
		IsFavorite: "isFavorite",
		MimeType:   "mimeType",
		FileSize:   "fileSize",
		FileExists: "fileExists",
		CreatedAt:  "createdAt",
		StatusID:   "statusId",

		Folder: "Folder",
	},
	VfsFolder: struct {
		ID, ParentFolderID, Title, IsFavorite, CreatedAt, StatusID string

		ParentFolder string
	}{
		ID:             "folderId",
		ParentFolderID: "parentFolderId",
		Title:          "title",
		IsFavorite:     "isFavorite",
		CreatedAt:      "createdAt",
		StatusID:       "statusId",

		ParentFolder: "ParentFolder",
	},
	Approach: struct {
		ID, ExerciseID, Reps, Weight, Duration, CreatedAt, StatusID string

		Exercise string
	}{
		ID:         "approachId",
		ExerciseID: "exerciseId",
		Reps:       "reps",
		Weight:     "weight",
		Duration:   "duration",
		CreatedAt:  "createdAt",
		StatusID:   "statusId",

		Exercise: "Exercise",
	},
	Category: struct {
		ID, ParentCategoryID, Title, SiteUserID, StatusID string

		ParentCategory, SiteUser string
	}{
		ID:               "categoryId",
		ParentCategoryID: "parentCategoryId",
		Title:            "title",
		SiteUserID:       "siteUserId",
		StatusID:         "statusId",

		ParentCategory: "ParentCategory",
		SiteUser:       "SiteUser",
	},
	Exercise: struct {
		ID, Title, CategoryID, SiteUserID, TypeID, StatusID string

		Category, SiteUser string
	}{
		ID:         "exerciseId",
		Title:      "title",
		CategoryID: "categoryId",
		SiteUserID: "siteUserId",
		TypeID:     "typeId",
		StatusID:   "statusId",

		Category: "Category",
		SiteUser: "SiteUser",
	},
	Training: struct {
		ID, SiteUserID, ApproachIDs, StartedAt, EndedAt, StatusID string

		SiteUser string
	}{
		ID:          "trainingId",
		SiteUserID:  "siteUserId",
		ApproachIDs: "approachIds",
		StartedAt:   "startedAt",
		EndedAt:     "endedAt",
		StatusID:    "statusId",

		SiteUser: "SiteUser",
	},
	SiteUser: struct {
		ID, TgID, CreatedAt, LastActivityAt, StatisticID, StatusID, ApiKey string
	}{
		ID:             "siteUserId",
		TgID:           "tgId",
		CreatedAt:      "createdAt",
		LastActivityAt: "lastActivityAt",
		StatisticID:    "statisticId",
		StatusID:       "statusId",
		ApiKey:         "apiKey",
	},
}

var Tables = struct {
	User struct {
		Name, Alias string
	}
	VfsFile struct {
		Name, Alias string
	}
	VfsFolder struct {
		Name, Alias string
	}
	Approach struct {
		Name, Alias string
	}
	Category struct {
		Name, Alias string
	}
	Exercise struct {
		Name, Alias string
	}
	Training struct {
		Name, Alias string
	}
	SiteUser struct {
		Name, Alias string
	}
}{
	User: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
	VfsFile: struct {
		Name, Alias string
	}{
		Name:  "vfsFiles",
		Alias: "t",
	},
	VfsFolder: struct {
		Name, Alias string
	}{
		Name:  "vfsFolders",
		Alias: "t",
	},
	Approach: struct {
		Name, Alias string
	}{
		Name:  "approaches",
		Alias: "t",
	},
	Category: struct {
		Name, Alias string
	}{
		Name:  "categories",
		Alias: "t",
	},
	Exercise: struct {
		Name, Alias string
	}{
		Name:  "exercises",
		Alias: "t",
	},
	Training: struct {
		Name, Alias string
	}{
		Name:  "trainings",
		Alias: "t",
	},
	SiteUser: struct {
		Name, Alias string
	}{
		Name:  "siteUsers",
		Alias: "t",
	},
}

type User struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID             int        `pg:"userId,pk"`
	Login          string     `pg:"login,use_zero"`
	Password       string     `pg:"password,use_zero"`
	AuthKey        *string    `pg:"authKey"`
	CreatedAt      time.Time  `pg:"createdAt,use_zero"`
	LastActivityAt *time.Time `pg:"lastActivityAt"`
	StatusID       int        `pg:"statusId,use_zero"`
}

type VfsFile struct {
	tableName struct{} `pg:"vfsFiles,alias:t,discard_unknown_columns"`

	ID         int       `pg:"fileId,pk"`
	FolderID   int       `pg:"folderId,use_zero"`
	Title      string    `pg:"title,use_zero"`
	Path       string    `pg:"path,use_zero"`
	Params     *string   `pg:"params"`
	IsFavorite *bool     `pg:"isFavorite"`
	MimeType   string    `pg:"mimeType,use_zero"`
	FileSize   *int      `pg:"fileSize"`
	FileExists bool      `pg:"fileExists,use_zero"`
	CreatedAt  time.Time `pg:"createdAt,use_zero"`
	StatusID   int       `pg:"statusId,use_zero"`

	Folder *VfsFolder `pg:"fk:folderId,rel:has-one"`
}

type VfsFolder struct {
	tableName struct{} `pg:"vfsFolders,alias:t,discard_unknown_columns"`

	ID             int       `pg:"folderId,pk"`
	ParentFolderID *int      `pg:"parentFolderId"`
	Title          string    `pg:"title,use_zero"`
	IsFavorite     *bool     `pg:"isFavorite"`
	CreatedAt      time.Time `pg:"createdAt,use_zero"`
	StatusID       int       `pg:"statusId,use_zero"`

	ParentFolder *VfsFolder `pg:"fk:parentFolderId,rel:has-one"`
}

type Approach struct {
	tableName struct{} `pg:"approaches,alias:t,discard_unknown_columns"`

	ID         int        `pg:"approachId,pk"`
	ExerciseID *int       `pg:"exerciseId"`
	Reps       *int       `pg:"reps"`
	Weight     *int       `pg:"weight"`
	Duration   *int       `pg:"duration"`
	CreatedAt  *time.Time `pg:"createdAt"`
	StatusID   int        `pg:"statusId,use_zero"`

	Exercise *Exercise `pg:"fk:exerciseId,rel:has-one"`
}

type Category struct {
	tableName struct{} `pg:"categories,alias:t,discard_unknown_columns"`

	ID               int    `pg:"categoryId,pk"`
	ParentCategoryID *int   `pg:"parentCategoryId"`
	Title            string `pg:"title,use_zero"`
	SiteUserID       *int   `pg:"siteUserId"`
	StatusID         int    `pg:"statusId,use_zero"`

	ParentCategory *Category `pg:"fk:parentCategoryId,rel:has-one"`
	SiteUser       *SiteUser `pg:"fk:siteUserId,rel:has-one"`
}

type Exercise struct {
	tableName struct{} `pg:"exercises,alias:t,discard_unknown_columns"`

	ID         int    `pg:"exerciseId,pk"`
	Title      string `pg:"title,use_zero"`
	CategoryID int    `pg:"categoryId,use_zero"`
	SiteUserID *int   `pg:"siteUserId"`
	TypeID     int    `pg:"typeId,use_zero"`
	StatusID   int    `pg:"statusId,use_zero"`

	Category *Category `pg:"fk:categoryId,rel:has-one"`
	SiteUser *SiteUser `pg:"fk:siteUserId,rel:has-one"`
}

type Training struct {
	tableName struct{} `pg:"trainings,alias:t,discard_unknown_columns"`

	ID          int        `pg:"trainingId,pk"`
	SiteUserID  int        `pg:"siteUserId,use_zero"`
	ApproachIDs []int      `pg:"approachIds,array"`
	StartedAt   time.Time  `pg:"startedAt,use_zero"`
	EndedAt     *time.Time `pg:"endedAt"`
	StatusID    int        `pg:"statusId,use_zero"`

	SiteUser *SiteUser `pg:"fk:siteUserId,rel:has-one"`
}

type SiteUser struct {
	tableName struct{} `pg:"siteUsers,alias:t,discard_unknown_columns"`

	ID             int        `pg:"siteUserId,pk"`
	TgID           int        `pg:"tgId,use_zero"`
	CreatedAt      time.Time  `pg:"createdAt,use_zero"`
	LastActivityAt *time.Time `pg:"lastActivityAt"`
	StatisticID    *int       `pg:"statisticId"`
	StatusID       int        `pg:"statusId,use_zero"`
	ApiKey         *string    `pg:"apiKey"`
}
