// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"

	"github.com/go-pg/pg/v10"
	"github.com/go-pg/pg/v10/orm"
)

const condition = "?.? = ?"

// base filters
type applier func(query *orm.Query) (*orm.Query, error)

type search struct {
	appliers []applier
}

func (s *search) apply(query *orm.Query) {
	for _, applier := range s.appliers {
		query.Apply(applier)
	}
}

func (s *search) where(query *orm.Query, table, field string, value interface{}) {
	query.Where(condition, pg.Ident(table), pg.Ident(field), value)
}

func (s *search) WithApply(a applier) {
	if s.appliers == nil {
		s.appliers = []applier{}
	}
	s.appliers = append(s.appliers, a)
}

func (s *search) With(condition string, params ...interface{}) {
	s.WithApply(func(query *orm.Query) (*orm.Query, error) {
		return query.Where(condition, params...), nil
	})
}

// Searcher is interface for every generated filter
type Searcher interface {
	Apply(query *orm.Query) *orm.Query
	Q() applier

	With(condition string, params ...interface{})
	WithApply(a applier)
}

type UserSearch struct {
	search

	ID             *int
	Login          *string
	Password       *string
	AuthKey        *string
	CreatedAt      *time.Time
	LastActivityAt *time.Time
	StatusID       *int
	IDs            []int
	LoginILike     *string
	AuthKeyILike   *string
}

func (us *UserSearch) Apply(query *orm.Query) *orm.Query {
	if us == nil {
		return query
	}
	if us.ID != nil {
		us.where(query, Tables.User.Alias, Columns.User.ID, us.ID)
	}
	if us.Login != nil {
		us.where(query, Tables.User.Alias, Columns.User.Login, us.Login)
	}
	if us.Password != nil {
		us.where(query, Tables.User.Alias, Columns.User.Password, us.Password)
	}
	if us.AuthKey != nil {
		us.where(query, Tables.User.Alias, Columns.User.AuthKey, us.AuthKey)
	}
	if us.CreatedAt != nil {
		us.where(query, Tables.User.Alias, Columns.User.CreatedAt, us.CreatedAt)
	}
	if us.LastActivityAt != nil {
		us.where(query, Tables.User.Alias, Columns.User.LastActivityAt, us.LastActivityAt)
	}
	if us.StatusID != nil {
		us.where(query, Tables.User.Alias, Columns.User.StatusID, us.StatusID)
	}
	if len(us.IDs) > 0 {
		Filter{Columns.User.ID, us.IDs, SearchTypeArray, false}.Apply(query)
	}
	if us.LoginILike != nil {
		Filter{Columns.User.Login, *us.LoginILike, SearchTypeILike, false}.Apply(query)
	}
	if us.AuthKeyILike != nil {
		Filter{Columns.User.AuthKey, *us.AuthKeyILike, SearchTypeILike, false}.Apply(query)
	}

	us.apply(query)

	return query
}

func (us *UserSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if us == nil {
			return query, nil
		}
		return us.Apply(query), nil
	}
}

type VfsFileSearch struct {
	search

	ID            *int
	FolderID      *int
	Title         *string
	Path          *string
	Params        *string
	IsFavorite    *bool
	MimeType      *string
	FileSize      *int
	FileExists    *bool
	CreatedAt     *time.Time
	StatusID      *int
	IDs           []int
	TitleILike    *string
	PathILike     *string
	ParamsILike   *string
	MimeTypeILike *string
}

func (vfs *VfsFileSearch) Apply(query *orm.Query) *orm.Query {
	if vfs == nil {
		return query
	}
	if vfs.ID != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.ID, vfs.ID)
	}
	if vfs.FolderID != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.FolderID, vfs.FolderID)
	}
	if vfs.Title != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.Title, vfs.Title)
	}
	if vfs.Path != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.Path, vfs.Path)
	}
	if vfs.Params != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.Params, vfs.Params)
	}
	if vfs.IsFavorite != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.IsFavorite, vfs.IsFavorite)
	}
	if vfs.MimeType != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.MimeType, vfs.MimeType)
	}
	if vfs.FileSize != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.FileSize, vfs.FileSize)
	}
	if vfs.FileExists != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.FileExists, vfs.FileExists)
	}
	if vfs.CreatedAt != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.CreatedAt, vfs.CreatedAt)
	}
	if vfs.StatusID != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.StatusID, vfs.StatusID)
	}
	if len(vfs.IDs) > 0 {
		Filter{Columns.VfsFile.ID, vfs.IDs, SearchTypeArray, false}.Apply(query)
	}
	if vfs.TitleILike != nil {
		Filter{Columns.VfsFile.Title, *vfs.TitleILike, SearchTypeILike, false}.Apply(query)
	}
	if vfs.PathILike != nil {
		Filter{Columns.VfsFile.Path, *vfs.PathILike, SearchTypeILike, false}.Apply(query)
	}
	if vfs.ParamsILike != nil {
		Filter{Columns.VfsFile.Params, *vfs.ParamsILike, SearchTypeILike, false}.Apply(query)
	}
	if vfs.MimeTypeILike != nil {
		Filter{Columns.VfsFile.MimeType, *vfs.MimeTypeILike, SearchTypeILike, false}.Apply(query)
	}

	vfs.apply(query)

	return query
}

func (vfs *VfsFileSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if vfs == nil {
			return query, nil
		}
		return vfs.Apply(query), nil
	}
}

type VfsFolderSearch struct {
	search

	ID             *int
	ParentFolderID *int
	Title          *string
	IsFavorite     *bool
	CreatedAt      *time.Time
	StatusID       *int
	IDs            []int
	TitleILike     *string
}

func (vfs *VfsFolderSearch) Apply(query *orm.Query) *orm.Query {
	if vfs == nil {
		return query
	}
	if vfs.ID != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.ID, vfs.ID)
	}
	if vfs.ParentFolderID != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.ParentFolderID, vfs.ParentFolderID)
	}
	if vfs.Title != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.Title, vfs.Title)
	}
	if vfs.IsFavorite != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.IsFavorite, vfs.IsFavorite)
	}
	if vfs.CreatedAt != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.CreatedAt, vfs.CreatedAt)
	}
	if vfs.StatusID != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.StatusID, vfs.StatusID)
	}
	if len(vfs.IDs) > 0 {
		Filter{Columns.VfsFolder.ID, vfs.IDs, SearchTypeArray, false}.Apply(query)
	}
	if vfs.TitleILike != nil {
		Filter{Columns.VfsFolder.Title, *vfs.TitleILike, SearchTypeILike, false}.Apply(query)
	}

	vfs.apply(query)

	return query
}

func (vfs *VfsFolderSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if vfs == nil {
			return query, nil
		}
		return vfs.Apply(query), nil
	}
}

type ApproachSearch struct {
	search

	ID         *int
	ExerciseID *int
	Reps       *int
	Weight     *int
	Duration   *int
	CreatedAt  *time.Time
	StatusID   *int
	IDs        []int
}

func (as *ApproachSearch) Apply(query *orm.Query) *orm.Query {
	if as == nil {
		return query
	}
	if as.ID != nil {
		as.where(query, Tables.Approach.Alias, Columns.Approach.ID, as.ID)
	}
	if as.ExerciseID != nil {
		as.where(query, Tables.Approach.Alias, Columns.Approach.ExerciseID, as.ExerciseID)
	}
	if as.Reps != nil {
		as.where(query, Tables.Approach.Alias, Columns.Approach.Reps, as.Reps)
	}
	if as.Weight != nil {
		as.where(query, Tables.Approach.Alias, Columns.Approach.Weight, as.Weight)
	}
	if as.Duration != nil {
		as.where(query, Tables.Approach.Alias, Columns.Approach.Duration, as.Duration)
	}
	if as.CreatedAt != nil {
		as.where(query, Tables.Approach.Alias, Columns.Approach.CreatedAt, as.CreatedAt)
	}
	if as.StatusID != nil {
		as.where(query, Tables.Approach.Alias, Columns.Approach.StatusID, as.StatusID)
	}
	if len(as.IDs) > 0 {
		Filter{Columns.Approach.ID, as.IDs, SearchTypeArray, false}.Apply(query)
	}

	as.apply(query)

	return query
}

func (as *ApproachSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if as == nil {
			return query, nil
		}
		return as.Apply(query), nil
	}
}

type CategorySearch struct {
	search

	ID               *int
	ParentCategoryID *int
	Title            *string
	SiteUserID       *int
	StatusID         *int
	IDs              []int
	TitleILike       *string
}

func (cs *CategorySearch) Apply(query *orm.Query) *orm.Query {
	if cs == nil {
		return query
	}
	if cs.ID != nil {
		cs.where(query, Tables.Category.Alias, Columns.Category.ID, cs.ID)
	}
	if cs.ParentCategoryID != nil {
		cs.where(query, Tables.Category.Alias, Columns.Category.ParentCategoryID, cs.ParentCategoryID)
	}
	if cs.Title != nil {
		cs.where(query, Tables.Category.Alias, Columns.Category.Title, cs.Title)
	}
	if cs.SiteUserID != nil {
		cs.where(query, Tables.Category.Alias, Columns.Category.SiteUserID, cs.SiteUserID)
	}
	if cs.StatusID != nil {
		cs.where(query, Tables.Category.Alias, Columns.Category.StatusID, cs.StatusID)
	}
	if len(cs.IDs) > 0 {
		Filter{Columns.Category.ID, cs.IDs, SearchTypeArray, false}.Apply(query)
	}
	if cs.TitleILike != nil {
		Filter{Columns.Category.Title, *cs.TitleILike, SearchTypeILike, false}.Apply(query)
	}

	cs.apply(query)

	return query
}

func (cs *CategorySearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if cs == nil {
			return query, nil
		}
		return cs.Apply(query), nil
	}
}

type ExerciseSearch struct {
	search

	ID         *int
	Title      *string
	CategoryID *int
	SiteUserID *int
	TypeID     *int
	StatusID   *int
	IDs        []int
	TitleILike *string
}

func (es *ExerciseSearch) Apply(query *orm.Query) *orm.Query {
	if es == nil {
		return query
	}
	if es.ID != nil {
		es.where(query, Tables.Exercise.Alias, Columns.Exercise.ID, es.ID)
	}
	if es.Title != nil {
		es.where(query, Tables.Exercise.Alias, Columns.Exercise.Title, es.Title)
	}
	if es.CategoryID != nil {
		es.where(query, Tables.Exercise.Alias, Columns.Exercise.CategoryID, es.CategoryID)
	}
	if es.SiteUserID != nil {
		es.where(query, Tables.Exercise.Alias, Columns.Exercise.SiteUserID, es.SiteUserID)
	}
	if es.TypeID != nil {
		es.where(query, Tables.Exercise.Alias, Columns.Exercise.TypeID, es.TypeID)
	}
	if es.StatusID != nil {
		es.where(query, Tables.Exercise.Alias, Columns.Exercise.StatusID, es.StatusID)
	}
	if len(es.IDs) > 0 {
		Filter{Columns.Exercise.ID, es.IDs, SearchTypeArray, false}.Apply(query)
	}
	if es.TitleILike != nil {
		Filter{Columns.Exercise.Title, *es.TitleILike, SearchTypeILike, false}.Apply(query)
	}

	es.apply(query)

	return query
}

func (es *ExerciseSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if es == nil {
			return query, nil
		}
		return es.Apply(query), nil
	}
}

type TrainingSearch struct {
	search

	ID              *int
	SiteUserID      *int
	StartedAt       *time.Time
	EndedAt         *time.Time
	StatusID        *int
	IDs             []int
	StartedAtGrater *time.Time
	StartedAtLess   *time.Time
}

func (ts *TrainingSearch) Apply(query *orm.Query) *orm.Query {
	if ts == nil {
		return query
	}
	if ts.ID != nil {
		ts.where(query, Tables.Training.Alias, Columns.Training.ID, ts.ID)
	}
	if ts.SiteUserID != nil {
		ts.where(query, Tables.Training.Alias, Columns.Training.SiteUserID, ts.SiteUserID)
	}
	if ts.StartedAt != nil {
		ts.where(query, Tables.Training.Alias, Columns.Training.StartedAt, ts.StartedAt)
	}
	if ts.EndedAt != nil {
		ts.where(query, Tables.Training.Alias, Columns.Training.EndedAt, ts.EndedAt)
	}
	if ts.StatusID != nil {
		ts.where(query, Tables.Training.Alias, Columns.Training.StatusID, ts.StatusID)
	}
	if len(ts.IDs) > 0 {
		Filter{Columns.Training.ID, ts.IDs, SearchTypeArray, false}.Apply(query)
	}
	if ts.StartedAtGrater != nil {
		Filter{Columns.Training.StartedAt, *ts.StartedAtGrater, SearchTypeGE, false}.Apply(query)
	}
	if ts.StartedAtLess != nil {
		Filter{Columns.Training.StartedAt, *ts.StartedAtLess, SearchTypeLE, false}.Apply(query)
	}

	ts.apply(query)

	return query
}

func (ts *TrainingSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if ts == nil {
			return query, nil
		}
		return ts.Apply(query), nil
	}
}

type SiteUserSearch struct {
	search

	ID             *int
	TgID           *int
	CreatedAt      *time.Time
	LastActivityAt *time.Time
	StatisticID    *int
	StatusID       *int
	IDs            []int
}

func (sus *SiteUserSearch) Apply(query *orm.Query) *orm.Query {
	if sus == nil {
		return query
	}
	if sus.ID != nil {
		sus.where(query, Tables.SiteUser.Alias, Columns.SiteUser.ID, sus.ID)
	}
	if sus.TgID != nil {
		sus.where(query, Tables.SiteUser.Alias, Columns.SiteUser.TgID, sus.TgID)
	}
	if sus.CreatedAt != nil {
		sus.where(query, Tables.SiteUser.Alias, Columns.SiteUser.CreatedAt, sus.CreatedAt)
	}
	if sus.LastActivityAt != nil {
		sus.where(query, Tables.SiteUser.Alias, Columns.SiteUser.LastActivityAt, sus.LastActivityAt)
	}
	if sus.StatisticID != nil {
		sus.where(query, Tables.SiteUser.Alias, Columns.SiteUser.StatisticID, sus.StatisticID)
	}
	if sus.StatusID != nil {
		sus.where(query, Tables.SiteUser.Alias, Columns.SiteUser.StatusID, sus.StatusID)
	}
	if len(sus.IDs) > 0 {
		Filter{Columns.SiteUser.ID, sus.IDs, SearchTypeArray, false}.Apply(query)
	}

	sus.apply(query)

	return query
}

func (sus *SiteUserSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if sus == nil {
			return query, nil
		}
		return sus.Apply(query), nil
	}
}
