// Code generated by colgen v0.1.2; DO NOT EDIT.
package workout

import (
	"workout/pkg/db"
)

type Approaches []Approach

func (ll Approaches) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll Approaches) Index() map[int]Approach {
	r := make(map[int]Approach, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewApproaches(in []db.Approach) Approaches { return MapP(in, NewApproach) }

type SiteUsers []SiteUser

func (ll SiteUsers) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll SiteUsers) Index() map[int]SiteUser {
	r := make(map[int]SiteUser, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewSiteUsers(in []db.SiteUser) SiteUsers { return MapP(in, NewSiteUser) }

type Trainings []Training

func (ll Trainings) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll Trainings) Index() map[int]Training {
	r := make(map[int]Training, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewTrainings(in []db.Training) Trainings { return MapP(in, NewTraining) }

func (ll Trainings) IndexByDate() map[string]Training {
	r := make(map[string]Training, len(ll))
	for i := range ll {
		r[ll[i].Date] = ll[i]
	}
	return r
}
