// Code generated by colgen v0.1.2; DO NOT EDIT.
package workout

import (
	"workoutbot/pkg/db"
)

type BotUsers []BotUser

func (ll BotUsers) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll BotUsers) Index() map[int]BotUser {
	r := make(map[int]BotUser, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewBotUsers(in []db.BotUser) BotUsers { return MapP(in, NewBotUser) }

type Trainings []Training

func (ll Trainings) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll Trainings) Index() map[int]Training {
	r := make(map[int]Training, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewTrainings(in []db.Training) Trainings { return MapP(in, NewTraining) }

func (ll Trainings) IndexByDate() map[string]Training {
	r := make(map[string]Training, len(ll))
	for i := range ll {
		r[ll[i].Date] = ll[i]
	}
	return r
}
