// Code generated by colgen v0.1.2; DO NOT EDIT.
package rpc

import (
	"workout/pkg/workout"
)

type Approaches []Approach

func (ll Approaches) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll Approaches) Index() map[int]Approach {
	r := make(map[int]Approach, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewApproaches(in []workout.Approach) Approaches { return workout.MapP(in, NewApproach) }

type Categories []Category

func (ll Categories) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll Categories) Index() map[int]Category {
	r := make(map[int]Category, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewCategories(in []workout.Category) Categories { return workout.MapP(in, NewCategory) }

type Exercises []Exercise

func (ll Exercises) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll Exercises) Index() map[int]Exercise {
	r := make(map[int]Exercise, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewExercises(in []workout.Exercise) Exercises { return workout.MapP(in, NewExercise) }

type Trainings []Training

func (ll Trainings) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll Trainings) Index() map[int]Training {
	r := make(map[int]Training, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewTrainings(in []workout.Training) Trainings { return workout.MapP(in, NewTraining) }
